### ISSUE TITLE
On Windows, modifying scores via ```zoxide edit``` results in a double slashed duplicate of the path

### ISSUE THREAD

**Issue by ciwolsey** [ajeetdsouza/zoxide#539]
Runnining ```zoxide edit``` on Windows and then attempting to increment or decrement a score causes the path to be added to the database again but with double slashes.

**Comment by WitchGod** [comment]
Confirming this is also happeing to me. Same as #538. Originally did it in Powershell 7/Core then got to replicate it in 5.1. Looks like a Windows bug. With the database serialized, I don't think it's an easy edit via source editor as well.

**Comment by princemaple** [comment]
Happening to me as well. Windows11, nushell.

**Comment by Bocom** [comment]
Happening to me as well, both this and #538.

**Comment by ArcusCerebellumus** [comment]
+1

**Comment by YDX-2147483647** [comment]
FYI, Swarnim Arun is drafting #569, which may fix all problems by distinguish `Path`/`PathBuf` from `str`/`String`. (And I suggest we stop +1 again and use the reaction emoji buttons 👍/🚀/…)

**Comment by hme3** [comment]
Any solution or workaround?

**Comment by MrDwarf7** [comment]
This seems to have been resolved, I no longer experience this either. (Was previously using Windows Terminal, now wezterm, $v tables below.

```powershell
 ❯ echo $PSVersionTable && Write-Host && wezterm -V # -->

Name                           Value
----                           -----
PSVersion                      7.6.0-preview.2
PSEdition                      Core
GitCommitId                    7.6.0-preview.2
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

wezterm 20240203-110809-5046fc22
```

This can likely be closed unless others are still experiencing this.

**Comment by YDX-2147483647** [comment]
I also confirm that this issue is resolved.

https://github.com/ajeetdsouza/zoxide/issues/539#issuecomment-1947825299 was posted on 2024-02-16, but https://github.com/ajeetdsouza/zoxide/releases/tag/v0.9.3 published on 2024-02-13 works as expected today. I guess the Windows system somehow changed and fixed the issue silently.

**Comment by ciwolsey** [comment]
I haven't experienced this issue for a long time now so it seems to be fixed and this can probably be closed off. Thanks all.

**Comment by tommdq** [comment]
I'm using zoxide with powershell and wezterm and still having this issue.

**Comment by tommdq** [comment]
> [@tommdq](https://github.com/tommdq) which version of zoxide?

![Image](https://github.com/user-attachments/assets/f8c35feb-984f-4189-9771-c98684bb6680)

0.9.7 . It keeps adding double \\ and creating a new path

**Comment by ciwolsey** [comment]
@tommdq very strange, I'm also on that 0.9.7 using Powershell but with Windows Terminal and no longer have the problem.

**Comment by YDX-2147483647** [comment]
> [#539 (comment)](https://github.com/ajeetdsouza/zoxide/issues/539#issuecomment-1947825299) was posted on 2024-02-16, but [`v0.9.3` (release)](https://github.com/ajeetdsouza/zoxide/releases/tag/v0.9.3) published on 2024-02-13 works as expected today. I guess the Windows system somehow changed and fixed the issue silently.

As I said before, this issue depends on the context.

@tommdq Could you share us with your $PSVersionTable? The following is mine, and it works.

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.0
PSEdition                      Core
GitCommitId                    7.5.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by tommdq** [comment]
> > [#539 (comment)](https://github.com/ajeetdsouza/zoxide/issues/539#issuecomment-1947825299) was posted on 2024-02-16, but [`v0.9.3` (release)](https://github.com/ajeetdsouza/zoxide/releases/tag/v0.9.3) published on 2024-02-13 works as expected today. I guess the Windows system somehow changed and fixed the issue silently.
> 
> As I said before, this issue depends on the context.
> 
> [@tommdq](https://github.com/tommdq) Could you share us with your $PSVersionTable? The following is mine, and it works.
> 
> > $PSVersionTable
> 
> Name                           Value
> ----                           -----
> PSVersion                      7.5.0
> PSEdition                      Core
> GitCommitId                    7.5.0
> OS                             Microsoft Windows 10.0.19045
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0

The only difference is my windows version: 

![Image](https://github.com/user-attachments/assets/a0be97c5-7703-41f6-a722-9e34b0c39453)

https://github.com/user-attachments/assets/8cb61816-40be-43f9-a58b-12f64fc179e7

I can delete but the increment and the decrement only keep creating new paths
I'm using wezterm and also have WSL with ubuntu and zoxide edit works as expected there.

**Comment by YDX-2147483647** [comment]
In February 2024, my zoxide behaved exactly like yours. `╮(╯_╰)╭` At least, we've ruled out the pwsh version as the cause.

> I'm using wezterm

Could you try to `zoxide edit` without wezterm?

1. Win+R, `pwsh -NoProfile`, enter.
2. Set up zoxide by executing `Invoke-Expression (& { (zoxide init powershell | Out-String) })`.
3. Try `zoxide edit`.

(It works on my machine.)

**Comment by ciwolsey** [comment]
Just for reference zoxide is now working for me using Windows Terminal / Powershell / 0.97. Here is my $PSVersion to help in your debugging:
```
Name                           Value
----                           -----
PSVersion                      5.1.26100.3624
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.26100.3624
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ciwolsey** [comment]
I updated, my $PSVersionTable now looks like:
```
Name                           Value
----                           -----
PSVersion                      7.5.0
PSEdition                      Core
GitCommitId                    7.5.0
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
It's still working as it should, no double slashes appearing.
Have you tried switching to Windows terminal?

**Comment by YDX-2147483647** [comment]
> Could it be related to the version of pwsh I'm using? (7.5.0)

Hmm, I also uses pwsh 7.5.0 core, and it works. 
I think we can conclude that tommdq's issue is related to neither the shell (pwsh version) nor the terminal emulator (wezterm / windows terminal)?

https://github.com/ajeetdsouza/zoxide/blob/e1e2f41ecbaceac855dd48c5064dc2b7aed8b0e6/src/cmd/edit.rs#L44-L47
`zoxide edit` depends on https://github.com/junegunn/fzf. Which version do you use? I use the following.

```powershell
> fzf --version
0.61.0 (e15cba0c)
```

**Comment by Aqaao** [comment]
> `zoxide edit` depends on https://github.com/junegunn/fzf.

Right. I updated my fzf (from 0.49 to 0.61) and it working fine now.

**Comment by YDX-2147483647** [comment]
> from 0.49 to 0.61

A quick bisect reveals that the first working version of fzf is https://github.com/junegunn/fzf/releases/tag/0.51.0, released on 2024-05-01, and its CHANGELOG said:
> Fixed argument escaping for Windows cmd.exe. No redundant escaping of backslashes.
https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0510

The key change was committed by junegunn in https://github.com/junegunn/fzf/commit/8d74446bef121b0dd3969611cf1d4a790d42b9ee and https://github.com/junegunn/fzf/commit/194a763c469e4fdbf31c0f71b1846add607477de, which closed https://github.com/junegunn/fzf/issues/3651#issuecomment-2081480129 and https://github.com/junegunn/fzf/issues/2609.

Now everything is clear. Time to close this issue!

**Comment by tommdq** [comment]
That was it. After updating fzf to version 0.61.0 zoxide edit is working as expected. Thanks to everyone !!! Issue solved

**Comment by LoicRiegel** [comment]
It would be nice to document it somewhere. Several tickets like this were opened.

There is this in the readme
```md
Install fzf (optional)

[fzf](https://github.com/junegunn/fzf) is a command-line fuzzy finder, used by zoxide for completions / interactive selection. It can be installed from [here](https://github.com/junegunn/fzf#installation).

Note zoxide only supports fzf v0.33.0 and above.
```

Maybe change it to something like:
```md
Note zoxide only supports fzf v0.33.0 and above (0.51.0 or above on Windows).
```
